version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: octavia_postgres
    environment:
      POSTGRES_DB: octavia_interview
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./database/dev-data.sql:/docker-entrypoint-initdb.d/02-dev-data.sql
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: octavia_redis
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  postgres_data: